name: Build and deploy Atenews Web Client
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: 
      name: Production
      url: https://atenews.ph
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Install dependencies
      working-directory: /var/www/atenews-frontend
      run: yarn

    - name: Build project
      working-directory: /var/www/atenews-frontend
      run: yarn build

    - name: Reload app
      working-directory: /var/www/atenews-frontend
      run: pm2 reload frontend
