name: Build and deploy Atenews Web Client
on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment:
      name: Production
      url: https://atenews.ph
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: production

    - name: Pull changes
      working-directory: /srv/atenews.ph/frontend
      run: git pull

    - name: Docker Compose build image
      working-directory: /srv/atenews.ph
      run: docker compose build

    - name: Recreate Docker container
      working-directory: /srv/atenews.ph
      run: docker compose up -d --force-recreate frontend
