name: Build and deploy Atenews Web Client (Prod)
on:
  push:
    branches:
      - production
jobs:
  build-image:
    name: Production - Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: latest=true

      - name: Docker - Build / Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-image:
    needs: build-image
    runs-on: self-hosted
    environment:
      name: Production
      url: https://atenews.ph
    steps:
      - name: Recreate Docker container
        working-directory: /srv/atenews.ph
        run: docker compose up -d --force-recreate --pull=always frontend